module QTCP

using QuantumSavory
import QuantumSavory: Tag, get_time_tracker
using QuantumSavory.ProtocolZoo
using QuantumSavory.ProtocolZoo: AbstractProtocol
import QuantumSavory.ProtocolZoo: protocol_catalog_metadata
using QuantumSavory.CircuitZoo: LocalEntanglementSwap
import ConcurrentSim
using ConcurrentSim: Simulation, @yield, timeout, @process, now, Process, Resource
import ResumableFunctions
using ResumableFunctions: @resumable
using DocStringExtensions
import Graphs

export QDatagram, Flow,
    LinkLevelRequest, LinkLevelReply, LinkLevelReplyAtHop, LinkLevelReplyAtSource,
    QTCPPairBegin, QTCPPairEnd,
    NetworkNodeController, EndNodeController, LinkController

###
# Message types
###

"""
$TYPEDEF

$TYPEDFIELDS
"""
@kwdef struct Flow <: AbstractTag
    "who initiates the request and also initiates the qdatagrams"
    src::Int
    "the destination node"
    dst::Int
    "the number of requested pairs"
    npairs::Int
    "the unique id of the flow"
    uuid::Int
end
Base.show(io::IO, tag::Flow) = print(io, "Flow `$(tag.uuid)` | $(tag.src) → $(tag.dst) | $(tag.npairs) pairs")
Tag(tag::Flow) = Tag(Flow, tag.src, tag.dst, tag.npairs, tag.uuid) # TODO automate this


"""
$TYPEDEF

$TYPEDFIELDS
"""
@kwdef struct QTCPPairBegin <: AbstractTag
    "the uuid of the flow we are generated for"
    flow_uuid::Int
    "who initiates the flow request and also initiates the qdatagrams"
    flow_src::Int
    "the destination node for the flow"
    flow_dst::Int
    "sequence number of the qdataframe in the given flow"
    seq_num::Int
    "the memory slot of the entangled qubit"
    memory_slot::Int
    "original start time of the qdatagram"
    start_time::Float64
end
Base.show(io::IO, tag::QTCPPairBegin) = print(io, "QTCPPairBegin `$(tag.flow_uuid).$(tag.seq_num)` $(tag.flow_src) → $(tag.flow_dst) | started at $(tag.start_time) | memory slot $(tag.memory_slot)")
Tag(tag::QTCPPairBegin) = Tag(QTCPPairBegin, tag.flow_uuid, tag.flow_src, tag.flow_dst, tag.seq_num, tag.memory_slot, tag.start_time) # TODO automate this


"""
$TYPEDEF

$TYPEDFIELDS
"""
@kwdef struct QTCPPairEnd <: AbstractTag
    "the uuid of the flow we are generated for"
    flow_uuid::Int
    "who initiates the flow request and also initiates the qdatagrams"
    flow_src::Int
    "the destination node for the flow"
    flow_dst::Int
    "sequence number of the qdataframe in the given flow"
    seq_num::Int
    "the memory slot of the entangled qubit"
    memory_slot::Int
    "original start time of the qdatagram"
    start_time::Float64
end
Base.show(io::IO, tag::QTCPPairEnd) = print(io, "QTCPPairEnd `$(tag.flow_uuid).$(tag.seq_num)` $(tag.flow_src) → $(tag.flow_dst) | started at $(tag.start_time) | memory slot $(tag.memory_slot)")
Tag(tag::QTCPPairEnd) = Tag(QTCPPairEnd, tag.flow_uuid, tag.flow_src, tag.flow_dst, tag.seq_num, tag.memory_slot, tag.start_time) # TODO automate this


"""
$TYPEDEF

$TYPEDFIELDS
"""
@kwdef struct QDatagram <: AbstractTag
    "the uuid of the flow we are generated for"
    flow_uuid::Int
    "who initiates the flow request and also initiates the qdatagrams"
    flow_src::Int
    "the destination node for the flow"
    flow_dst::Int
    "the Pauli frame correction"
    correction::Int
    "sequence number of the qdataframe in the given flow"
    seq_num::Int
    "original start time of the qdatagram"
    start_time::Float64
end
Base.show(io::IO, tag::QDatagram) = print(io, "QDatagram `$(tag.flow_uuid).$(tag.seq_num)` $(tag.flow_src) → $(tag.flow_dst) | started at $(tag.start_time) | correction $(tag.correction)")
Tag(tag::QDatagram) = Tag(QDatagram, tag.flow_uuid, tag.flow_src, tag.flow_dst, tag.correction, tag.seq_num, tag.start_time) # TODO automate this

"""
$TYPEDEF

$TYPEDFIELDS
"""
@kwdef struct QDatagramSuccess <: AbstractTag
    "the uuid of the flow we are generated for"
    flow_uuid::Int
    "sequence number of the qdataframe in the given flow"
    seq_num::Int
    "time at which the qdatagram was generated by the flow source"
    start_time::Float64
end
Base.show(io::IO, tag::QDatagramSuccess) = print(io, "QDatagramSuccess `$(tag.flow_uuid).$(tag.seq_num)` | started at $(tag.start_time)")
Tag(tag::QDatagramSuccess) = Tag(QDatagramSuccess, tag.flow_uuid, tag.seq_num, tag.start_time) # TODO automate this

"""
$TYPEDEF

$TYPEDFIELDS
"""
@kwdef struct LinkLevelRequest <: AbstractTag
    "the uuid of the flow we are providing entanglement for"
    flow_uuid::Int
    "sequence number of the qdataframe we are providing entanglement for"
    seq_num::Int
    "the remote node with which we want to establish entanglement"
    remote_node::Int
end
Base.show(io::IO, tag::LinkLevelRequest) = print(io, "LinkLevelRequest for flow $(tag.flow_uuid), sequence $(tag.seq_num), remote node $(tag.remote_node)")
Tag(tag::LinkLevelRequest) = Tag(LinkLevelRequest, tag.flow_uuid, tag.seq_num, tag.remote_node) # TODO automate this

"""
$TYPEDEF

$TYPEDFIELDS
"""
@kwdef struct LinkLevelReply <: AbstractTag
    "the uuid of the flow we are providing entanglement for"
    flow_uuid::Int
    "sequence number of the qdataframe we are providing entanglement for"
    seq_num::Int
    "where is the entangled qubit stored"
    memory_slot::Int
end
Base.show(io::IO, tag::LinkLevelReply) = print(io, "LinkLevelReply for flow $(tag.flow_uuid), sequence $(tag.seq_num), memory slot $(tag.memory_slot)")
Tag(tag::LinkLevelReply) = Tag(LinkLevelReply, tag.flow_uuid, tag.seq_num, tag.memory_slot) # TODO automate this

"""
$TYPEDEF

$TYPEDFIELDS
"""
@kwdef struct LinkLevelReplyAtSource <: AbstractTag
    "the uuid of the flow we are providing entanglement for"
    flow_uuid::Int
    "sequence number of the qdataframe we are providing entanglement for"
    seq_num::Int
    "where is the entangled qubit stored"
    memory_slot::Int
end
Base.show(io::IO, tag::LinkLevelReplyAtSource) = print(io, "LinkLevelReplyAtSource for flow $(tag.flow_uuid), sequence $(tag.seq_num), memory slot $(tag.memory_slot)")
Tag(tag::LinkLevelReplyAtSource) = Tag(LinkLevelReplyAtSource, tag.flow_uuid, tag.seq_num, tag.memory_slot) # TODO automate this

"""
$TYPEDEF

$TYPEDFIELDS
"""
@kwdef struct LinkLevelReplyAtHop <: AbstractTag
    "the uuid of the flow we are providing entanglement for"
    flow_uuid::Int
    "sequence number of the qdataframe we are providing entanglement for"
    seq_num::Int
    "where is the entangled qubit stored"
    memory_slot::Int
end
Base.show(io::IO, tag::LinkLevelReplyAtHop) = print(io, "LinkLevelReplyAtHop for flow $(tag.flow_uuid), sequence $(tag.seq_num), memory slot $(tag.memory_slot)")
Tag(tag::LinkLevelReplyAtHop) = Tag(LinkLevelReplyAtHop, tag.flow_uuid, tag.seq_num, tag.memory_slot) # TODO automate this


###
# Protocol declaration
###

const _EndNodeFlowStats = @NamedTuple{
    flow_src::Int,
    flow_dst::Int,
    delivered::Int,
    latency_sum::Float64,
    flow_start_time::Float64,
    last_delivery_time::Float64,
}

"""
$TYPEDEF

$FIELDS

Managing the following transformations of classical control signals:

- `Flow` @ start node → sequence of `QDatagram` @ start node
- `QDatagramSuccess` received from destination node → continuing the flow's sequence, reevaluating window
    - and converting `LinkLevelReplyAtSource` to `QTCPPairBegin`
- `QDatagram` @ destination node → `QDatagramSuccess` sent to start node
    - and converting `LinkLevelReplyAtHop` to `QTCPPairEnd`
"""
@kwdef struct EndNodeController <: AbstractProtocol
    """time-and-schedule-tracking instance from `ConcurrentSim`"""
    sim::Simulation
    """a network graph of registers"""
    net::RegisterNet
    """the vertex index of where the protocol is located"""
    node::Int
    """internal per-flow delivery statistics retained for visualization"""
    _log::Dict{Int,_EndNodeFlowStats} = Dict{Int,_EndNodeFlowStats}()
end

protocol_catalog_metadata(::Type{EndNodeController}) = (
    attachment = :node,
    attachment_fields = (node=:node,),
    required_fields = (),
)

EndNodeController(sim::Simulation, net::RegisterNet, node::Int) =
    EndNodeController(; sim, net, node)
EndNodeController(net::RegisterNet, node::Int) = EndNodeController(get_time_tracker(net), net, node)

"Create empty delivery statistics for one flow."
function _empty_endnode_flow_stats(flow_src::Int, flow_dst::Int, flow_start_time::Float64)
    return (;
        flow_src,
        flow_dst,
        delivered=0,
        latency_sum=0.0,
        flow_start_time,
        last_delivery_time=flow_start_time,
    )
end

"Record one delivered pair for a flow."
function _record_endnode_delivery!(
    prot::EndNodeController,
    flow_uuid::Int,
    flow_src::Int,
    flow_dst::Int,
    start_time::Float64,
)
    delivery_time = now(prot.sim)::Float64
    stats = get(prot._log, flow_uuid, _empty_endnode_flow_stats(
        flow_src, flow_dst, start_time
    ))
    prot._log[flow_uuid] = (;
        stats...,
        delivered=stats.delivered + 1,
        latency_sum=stats.latency_sum + delivery_time - start_time,
        flow_start_time=min(stats.flow_start_time, start_time),
        last_delivery_time=max(stats.last_delivery_time, delivery_time),
    )
    return nothing
end

"""
$TYPEDEF

$FIELDS

Managing the following transformations of classical control signals:

- `QDatagram` → `LinkLevelRequest` to link with next hop (according to a pathfinding algorithm)
- `LinkLevelReply` → `QDatagram` forwarded to next hop and
    - either a swap with the pre-existing `LinkLevelReplyAtHop`
    - or just tagging `LinkLevelReplyAtSource` if we are at the source node of the flow
- this is the entity that actually:
    - performs pathfinding
    - performs entanglement swapping
"""
@kwdef struct NetworkNodeController <: AbstractProtocol
    """time-and-schedule-tracking instance from `ConcurrentSim`"""
    sim::Simulation
    """a network graph of registers"""
    net::RegisterNet
    """the vertex index of where the protocol is located"""
    node::Int
    """stores queue events used by protocol visualizations; the storage type is not part of the public API and may change in future versions"""
    _log::Vector{@NamedTuple{t::Float64, flow_id::Int, processed::Bool, sojourn::Float64}} = @NamedTuple{t::Float64, flow_id::Int, processed::Bool, sojourn::Float64}[]
end

protocol_catalog_metadata(::Type{NetworkNodeController}) = (
    attachment = :node,
    attachment_fields = (node=:node,),
    required_fields = (),
)

function NetworkNodeController(sim, net, node; kwargs...)
    return NetworkNodeController(;sim, net, node, kwargs...)
end
function NetworkNodeController(net::RegisterNet, node::Int; kwargs...)
    return NetworkNodeController(get_time_tracker(net), net, node; kwargs...)
end

const _LinkControllerLogEntry = @NamedTuple{
    originator_node::Int,
    arrival_time::Float64,
    sojourn_time::Union{Nothing,Float64},
}

"""
$TYPEDEF

$FIELDS

Managing the following transformations of classical control signals:

- `LinkLevelRequest` → `LinkLevelReply` and `LinkLevelReplyAtHop`
- this is the entity that actually establishes the link-level entanglement
"""
@kwdef struct LinkController <: AbstractProtocol
    """time-and-schedule-tracking instance from `ConcurrentSim`"""
    sim::Simulation
    """a network graph of registers"""
    net::RegisterNet
    """the vertex index of one of the nodes in the link (Alice)"""
    nodeA::Int
    """the vertex index of one of the nodes in the link (Bob)"""
    nodeB::Int
    """`nothing` to generate entanglement for each request, or a concrete `AbstractTag` subtype identifying externally generated entanglement to consume"""
    tag::Union{Nothing,Type{<:AbstractTag}} = nothing
    """inventory selection order: `true` takes the newest pair and `false` the oldest; must be `nothing` when `tag` is `nothing`"""
    filo::Union{Nothing,Bool} = isnothing(tag) ? nothing : true
    """request arrival and sojourn records; the storage type is not part of the public API and may change in future versions"""
    _log::Vector{_LinkControllerLogEntry} = _LinkControllerLogEntry[]

    function LinkController(sim, net, nodeA, nodeB, tag, filo, _log)
        if isnothing(tag)
            isnothing(filo) || throw(ArgumentError(
                "`filo` must be `nothing` when `LinkController` generates entanglement"
            ))
        else
            isconcretetype(tag) || throw(ArgumentError(
                "`tag` must be a concrete subtype of `AbstractTag`"
            ))
            filo isa Bool || throw(ArgumentError(
                "`filo` must be a `Bool` when `LinkController` uses external inventory"
            ))
        end
        return new(sim, net, nodeA, nodeB, tag, filo, _log)
    end
end

protocol_catalog_metadata(::Type{LinkController}) = (
    attachment = :edge,
    attachment_fields = (node_a=:nodeA, node_b=:nodeB),
    required_fields = (),
)

function LinkController(
    sim::Simulation, net::RegisterNet, nodeA::Int, nodeB::Int; kwargs...
)
    return LinkController(; sim, net, nodeA, nodeB, kwargs...)
end

function LinkController(net::RegisterNet, nodeA::Int, nodeB::Int; kwargs...)
    return LinkController(get_time_tracker(net), net, nodeA, nodeB; kwargs...)
end


###
# Protocol Implementation
###

@resumable function (prot::EndNodeController)()
    (;sim, net, node) = prot
    mb = messagebuffer(net, node)

    current_flows = Set{Int}() # the uuids of flows currently being processed
    # these are keyed by uuid:
    qdatagrams_in_flight   = Dict{Int,Int}() # number of datagrams currently believed to be in flight # TODO turn value to ordered list
    qdatagrams_sent        = Dict{Int,Int}() # total number of datagrams already sent
    pairs_left_to_fulfill = Dict{Int,Int}() # total number of pairs still to be established
    destination            = Dict{Int,Int}() # the destination

    WINDOW = 3 # TODO per flow

    while true
        workwasdone = true
        while workwasdone
            workwasdone = false

            # check if there is an approved flow and start it
            flow = querydelete!(mb, Flow, node, ❓, ❓, ❓)
            if !isnothing(flow)
                workwasdone = true
                _, _, dst, npairs, uuid = flow.tag
                push!(current_flows, uuid)
                qdatagrams_in_flight[uuid]   = 0
                qdatagrams_sent[uuid]        = 0
                pairs_left_to_fulfill[uuid] = npairs
                destination[uuid]            = dst
                get!(prot._log, uuid) do
                    _empty_endnode_flow_stats(node, dst, now(sim)::Float64)
                end
                @debug(
                    "Started a flow",
                    _group=LOG_GROUPS.protocol,
                    event=:flow_started,
                    protocol_log_context(prot)...,
                    flow_id=uuid,
                    src_node=node,
                    dst_node=dst,
                )
            end

            # check if there are datagram acknowledgements
            success = querydelete!(mb, QDatagramSuccess, ❓, ❓, ❓)
            if !isnothing(success)
                workwasdone = true
                # TODO implement drop detection and window modification
                _, flow_uuid, seq_num, start_time = success.tag
                start_time = start_time::Float64
                qdatagrams_in_flight[flow_uuid]   -= 1
                pairs_left_to_fulfill[flow_uuid] -= 1

                # Check if there are any LinkLevelReplyAtSource messages and turn them into QTCPPairBegin messages
                link_reply = querydelete!(mb, LinkLevelReplyAtSource, flow_uuid, seq_num, ❓)
                @assert !isnothing(link_reply) "No LinkLevelReplyAtSource message found after the success of flow $(flow_uuid), sequence $(seq_num) at node $(node)"
                _, _, _, memory_slot = link_reply.tag
                pair_begin = QTCPPairBegin(;
                    flow_uuid,
                    flow_src=node,
                    flow_dst=success.src,
                    seq_num,
                    memory_slot,
                    start_time
                )
                put!(net[node], pair_begin)
                _record_endnode_delivery!(
                    prot, flow_uuid, node, success.src, start_time
                )
                @debug(
                    "Acknowledged a datagram",
                    _group=LOG_GROUPS.protocol,
                    event=:datagram_acknowledged,
                    protocol_log_context(prot)...,
                    flow_id=flow_uuid,
                    sequence_number=seq_num,
                    src_node=success.src,
                    dst_node=node,
                )

                # if we have fulfilled all pairs, remove the flow in every data structure
                if pairs_left_to_fulfill[flow_uuid] == 0
                    delete!(current_flows, flow_uuid)
                    delete!(qdatagrams_in_flight, flow_uuid)
                    delete!(qdatagrams_sent, flow_uuid)
                    delete!(pairs_left_to_fulfill, flow_uuid)
                    delete!(destination, flow_uuid)
                    @debug(
                        "Completed a flow",
                        _group=LOG_GROUPS.protocol,
                        event=:flow_completed,
                        protocol_log_context(prot)...,
                        flow_id=flow_uuid,
                    )
                end
            end

            # check if we just received a qdatagram for which we are the flow destination
            qdatagram = querydelete!(mb, QDatagram, ❓, ❓, node, ❓, ❓, ❓)
            if !isnothing(qdatagram)
                workwasdone = true
                # We need to generate a QDatagramSuccess message and send it back to the flow source
                _, flow_uuid, flow_src, flow_dst, corrections, seq_num, start_time = qdatagram.tag
                start_time = start_time::Float64
                qdatagram_success = QDatagramSuccess(flow_uuid, seq_num, start_time)
                put!(channel(net, node=>flow_src; permit_forward=true), qdatagram_success)
                # TODO implement Pauli corrections

                # Check if there are any LinkLevelReplyAtHop messages and turn them into QTCPPairEnd messages
                link_reply = querydelete!(mb, LinkLevelReplyAtHop, flow_uuid, seq_num, ❓)
                @assert !isnothing(link_reply) "No LinkLevelReplyAtHop message found after the success of flow $(flow_uuid), sequence $(seq_num) at node $(node)"
                _, _, _, memory_slot = link_reply.tag
                pair_end = QTCPPairEnd(;
                    flow_uuid,
                    flow_src=flow_src,
                    flow_dst=node,
                    seq_num,
                    memory_slot,
                    start_time
                )
                put!(net[node], pair_end)
                _record_endnode_delivery!(
                    prot, flow_uuid, flow_src, flow_dst, start_time
                )
                @debug(
                    "Delivered a datagram",
                    _group=LOG_GROUPS.protocol,
                    event=:datagram_delivered,
                    protocol_log_context(prot)...,
                    flow_id=flow_uuid,
                    sequence_number=seq_num,
                    src_node=flow_src,
                    dst_node=node,
                )
            end
        end

        # send qdatagrams
        for uuid in current_flows
            while qdatagrams_in_flight[uuid] < WINDOW && qdatagrams_in_flight[uuid] < pairs_left_to_fulfill[uuid]
                qdatagrams_in_flight[uuid] += 1
                dst        = destination[uuid]
                seq_num    = qdatagrams_sent[uuid] += 1
                start_time = now(sim)::Float64
                corrections = 0 # TODO implement Pauli corrections
                qdatagram = QDatagram(uuid, node, dst, corrections, seq_num, start_time)
                put!(net[node], qdatagram)
            end
        end

        # wait until we have received a message
        @yield onchange(mb)
    end
end


@resumable function (prot::NetworkNodeController)()
    (;sim, net, node) = prot
    mb = messagebuffer(net, node)
    datagrams_in_waiting = Dict{Tuple{Int,Int},Tuple{Tag,Int,Float64}}() # keyed by flow_uuid, seq_num; storing datagram tag, next hop, and enqueue time
    while true
        workwasdone = true
        while workwasdone
            workwasdone = false

            incoming_qdatagram = querydelete!(mb, QDatagram, ❓, ❓, !=(node), ❓, ❓, ❓)
            if !isnothing(incoming_qdatagram)
                workwasdone = true
                _, flow_uuid, flow_src, flow_dst, corrections, seq_num, start_time = incoming_qdatagram.tag
                nexthop = first(Graphs.a_star(net.graph, node, flow_dst::Int)).dst
                request = LinkLevelRequest(flow_uuid, seq_num, nexthop)
                enqueued_at = now(sim)::Float64
                datagrams_in_waiting[(flow_uuid, seq_num)] = (incoming_qdatagram.tag, nexthop, enqueued_at)
                push!(prot._log, (t=enqueued_at, flow_id=flow_uuid, processed=false, sojourn=0.0))
                put!(mb, request)
            end

            # Check for LinkLevelReply messages
            # TODO have timeouts on how long to wait for a reply
            llreply = querydelete!(mb, LinkLevelReply, ❓, ❓, ❓)
            if !isnothing(llreply)
                workwasdone = true
                _, flow_uuid, seq_num, memory_slot = llreply.tag
                # Find the corresponding QDatagram that matches this reply
                queued_tag, nexthop, enqueued_at = pop!(datagrams_in_waiting, (flow_uuid, seq_num))
                # Process the entanglement and forward the datagram
                _, flow_uuid, flow_src, flow_dst, corrections, seq_num, start_time = queued_tag

                # Perform entanglement swapping
                if node == flow_src
                    put!(net[node], LinkLevelReplyAtSource(flow_uuid, seq_num, memory_slot))
                else
                    # Find the corresponding LinkLevelReplyAtHop message from the previous hop (when the current node was the destination node)
                    llreply_at_destination = querydelete!(mb, LinkLevelReplyAtHop, flow_uuid, seq_num, ❓)
                    @assert !isnothing(llreply_at_destination) "No LinkLevelReplyAtHop message found for flow $(flow_uuid), sequence $(seq_num) at node $(node)"
                    _, _, _, memory_slot_at_destination = llreply_at_destination.tag
                    swapcircuit = LocalEntanglementSwap()
                    xmeas, zmeas = swapcircuit(net[node,memory_slot], net[node,memory_slot_at_destination])
                    # TODO: use xmeas and zmeas to add a correction to the datagram
                end

                # Forward the datagram to the next node in the path
                new_qdatagram = QDatagram(flow_uuid, flow_src, flow_dst, corrections, seq_num, start_time)
                put!(channel(net, node=>nexthop; permit_forward=false), new_qdatagram)
                processed_at = now(sim)::Float64
                push!(prot._log, (t=processed_at, flow_id=flow_uuid, processed=true, sojourn=processed_at-enqueued_at))
            end
        end

        # Wait until we have received a message
        @yield onchange(mb)
    end
end


"""Create the `EntanglerProt` used by a `LinkController`."""
function _link_entangler(prot::LinkController)
    (; sim, net, nodeA, nodeB) = prot
    return EntanglerProt(;
        sim, net,
        nodeA, nodeB,
        tag=nothing,
        rounds=1,
        attempts=-1,
        success_prob=1.0,
        attempt_time=1.0, # TODO parameterize the link time and quality
    )
end

"""Return external-inventory candidates in the configured selection order."""
function _link_inventory_candidates(
    prot::LinkController
)
    tag = prot.tag::DataType
    filo = prot.filo::Bool
    if tag === EntanglementCounterpart
        return queryall(
            prot.net[prot.nodeA], tag, prot.nodeB, ❓, ❓; filo, assigned=true
        )
    end
    return queryall(
        prot.net[prot.nodeA], tag, prot.nodeB, ❓; filo, assigned=true
    )
end

"""Find the exact reciprocal tag for an external-inventory candidate."""
function _link_inventory_reciprocal(
    prot::LinkController,
    candidate,
)
    remote_slot = candidate.tag[3]::Int
    destination_register = prot.net[prot.nodeB]
    1 <= remote_slot <= length(destination_register) || return nothing

    tag = prot.tag::DataType
    filo = prot.filo::Bool
    remote = destination_register[remote_slot]
    if tag === EntanglementCounterpart
        pair_id = candidate.tag[4]::Int
        return query(
            remote, tag, prot.nodeA, candidate.slot.idx, pair_id;
            filo, assigned=true
        )
    end
    return query(
        remote, tag, prot.nodeA, candidate.slot.idx; filo, assigned=true
    )
end

"""Return configured inventory tags on one slot."""
function _link_inventory_slot_tags(
    prot::LinkController,
    slot;
    locked::Union{Nothing,Bool}=nothing,
    assigned::Union{Nothing,Bool}=nothing,
)
    tag = prot.tag::DataType
    if tag === EntanglementCounterpart
        return queryall(slot, tag, ❓, ❓, ❓; locked, assigned)
    end
    return queryall(slot, tag, ❓, ❓; locked, assigned)
end

"""Check that a result is the unique configured inventory tag on its slot."""
function _link_inventory_tag_is_unique(
    prot::LinkController,
    result;
    locked::Union{Nothing,Bool}=nothing,
    assigned::Union{Nothing,Bool}=nothing,
)
    current = _link_inventory_slot_tags(prot, result.slot; locked, assigned)
    return length(current) == 1 &&
        only(current).id == result.id &&
        only(current).tag == result.tag
end

"""Wait for and atomically claim one reciprocal pair from external inventory."""
@resumable function _link_claim_inventory_pair(
    sim::Simulation,
    prot::LinkController,
)
    register_a = prot.net[prot.nodeA]
    register_b = prot.net[prot.nodeB]

    while true
        retry = false
        candidates = _link_inventory_candidates(prot)
        for candidate in candidates
            reciprocal = _link_inventory_reciprocal(prot, candidate)
            isnothing(reciprocal) && continue
            _link_inventory_tag_is_unique(
                prot, candidate; assigned=true
            ) || continue
            _link_inventory_tag_is_unique(
                prot, reciprocal; assigned=true
            ) || continue

            slot_a = candidate.slot
            slot_b = reciprocal.slot
            state_a = QuantumSavory.stateof(slot_a)
            state_b = QuantumSavory.stateof(slot_b)
            state_a === state_b || continue
            @yield @process nongreedymultilock(
                sim, (slot_a, slot_b)
            )

            valid = isassigned(slot_a) &&
                isassigned(slot_b) &&
                QuantumSavory.stateof(slot_a) === state_a &&
                QuantumSavory.stateof(slot_b) === state_b &&
                _link_inventory_tag_is_unique(
                    prot, candidate; locked=true, assigned=true
                ) &&
                _link_inventory_tag_is_unique(
                    prot, reciprocal; locked=true, assigned=true
                )
            if valid
                untag!(slot_a, candidate.id)
                untag!(slot_b, reciprocal.id)
                unlock(slot_a)
                unlock(slot_b)
                return slot_a.idx, slot_b.idx
            end

            unlock(slot_a)
            unlock(slot_b)
            retry = true
            break
        end
        retry && continue

        @yield onchange(register_a, Tag) | onchange(register_b, Tag)
    end
end

@resumable function _link_handle_request(
    sim::Simulation,
    prot::LinkController,
    originator_node::Int,
    destination_node::Int,
    flow_uuid::Int,
    seq_num::Int,
    link_resource,
    log_index::Int,
)
    (; net, nodeA, nodeB) = prot
    @yield lock(link_resource)
    slotA = 0
    slotB = 0
    if isnothing(prot.tag)
        entangler = _link_entangler(prot)
        # TODO have a timeout on how long to wait for an entangler to complete
        proc = @process entangler()
        _, slotA, _, slotB = @yield proc
    else
        claim = @process _link_claim_inventory_pair(sim, prot)
        slotA, slotB = @yield claim
    end
    unlock(link_resource)
    # Map the canonical endpoint slots to the request direction.
    originator_slot, destination_slot = originator_node == nodeA ?
        (slotA, slotB) : (slotB, slotA)
    put!(net[originator_node], LinkLevelReply(flow_uuid=flow_uuid, seq_num=seq_num, memory_slot=originator_slot))
    put!(net[destination_node], LinkLevelReplyAtHop(flow_uuid=flow_uuid, seq_num=seq_num, memory_slot=destination_slot))
    entry = prot._log[log_index]
    prot._log[log_index] = (
        originator_node=entry.originator_node,
        arrival_time=entry.arrival_time,
        sojourn_time=(now(sim)::Float64) - entry.arrival_time,
    )
end

@resumable function (prot::LinkController)()
    (;sim, net, nodeA, nodeB) = prot
    mbA = messagebuffer(net, nodeA)
    mbB = messagebuffer(net, nodeB)
    link_resource = Resource(sim, 1)

    while true
        workwasdone = true
        while workwasdone
            workwasdone = false

            llrequestA = querydelete!(mbA, LinkLevelRequest, ❓, ❓, nodeB)
            llrequest, originator_node, destination_node = if isnothing(llrequestA)
                querydelete!(mbB, LinkLevelRequest, ❓, ❓, nodeA), nodeB, nodeA
            else
                llrequestA, nodeA, nodeB
            end
            if !isnothing(llrequest)
                workwasdone = true
                @assert originator_node != destination_node "LinkController $(nodeA) $(nodeB) has a link request with originator node $(originator_node) equal to the destination node $(destination_node)"
                _, flow_uuid, seq_num, remote_node = llrequest.tag
                push!(prot._log, (
                    originator_node=originator_node::Int,
                    arrival_time=now(sim)::Float64,
                    sojourn_time=nothing,
                ))
                log_index = lastindex(prot._log)
                @process _link_handle_request(
                    sim,
                    prot,
                    originator_node,
                    destination_node,
                    flow_uuid,
                    seq_num,
                    link_resource,
                    log_index,
                )
            end
        end
        # wait until we have received a message
        @yield (onchange(mbA) | onchange(mbB))
    end
end

include("qtcp/show.jl")

end # module
