env:
  JULIA_NUM_THREADS: auto

secrets:
  - CODECOV_TOKEN

steps:
  - label: "General Tests"
    plugins:
      - QuantumSavory/julia#v1:
          version: "1"
      - QuantumSavory/julia-xvfb#v1:
      - JuliaCI/julia-test#v1:
          test_args: "general"
      - JuliaCI/julia-coverage#v1: ~
  - label: "General Tests (alpha)"
    plugins:
      - QuantumSavory/julia#v1:
          version: "alpha"
      - QuantumSavory/julia-xvfb#v1:
      - JuliaCI/julia-test#v1:
          test_args: "general"
      - JuliaCI/julia-coverage#v1: ~
  - label: "JET Tests"
    # Avoid the parallel compiler cache race until Julia includes this fix:
    # https://github.com/JuliaLang/julia/pull/62332
    env:
      JULIA_NUM_THREADS: "1"
    plugins:
      - QuantumSavory/julia#v1:
          version: "1"
      - QuantumSavory/julia-xvfb#v1:
      - JuliaCI/julia-test#v1:
          test_args: "jet"
      - JuliaCI/julia-coverage#v1: ~
  - label: "Example Tests"
    plugins:
      - QuantumSavory/julia#v1:
          version: "1"
      - QuantumSavory/julia-xvfb#v1:
      - JuliaCI/julia-test#v1:
          test_args: "example"
      - JuliaCI/julia-coverage#v1: ~
  - label: "Plotting Tests"
    plugins:
      - QuantumSavory/julia#v1:
          version: "1"
      - QuantumSavory/julia-xvfb#v1:
      - JuliaCI/julia-test#v1:
          test_args: "plotting"
      - JuliaCI/julia-coverage#v1: ~
    secrets:
      - TILE_CI_KEY
  - label: "Docs"
    branches: "!dependabot/*"
    plugins:
      - QuantumSavory/julia#v1:
          version: "1"
      - QuantumSavory/julia-xvfb#v1:
    secrets:
      - DOCUMENTER_KEY
      - ANYTHINGLLM_API_KEY
      - TILE_CI_KEY
    command: |
      julia --project=docs -e 'using Pkg; Pkg.instantiate()'
      julia -tauto --project=docs docs/make.jl
