env:
  JULIA_NUM_THREADS: auto

secrets:
  - CODECOV_TOKEN

# Pin portable hooks until these fixes are released:
# https://github.com/JuliaCI/julia-buildkite-plugin/pull/64
# https://github.com/QuantumSavory/julia-xvfb-buildkite-plugin/pull/1
steps:
  - label: "General Tests"
    plugins:
      - JuliaCI/julia#fb9fb9196677350a913f82a125113cc31238ad31:
          version: "1"
      - QuantumSavory/julia-xvfb#a92371896a8ab82b8cbd9a28973003df16a2f58d:
      - JuliaCI/julia-test#v1:
          test_args: "general"
      - JuliaCI/julia-coverage#v1: ~
  - label: "General Tests (alpha)"
    plugins:
      - Krastanov-agent/julia#02e5970063da49f1c9a2d04d3250b95fa3a9fb7b:
          version: "alpha"
      - QuantumSavory/julia-xvfb#a92371896a8ab82b8cbd9a28973003df16a2f58d:
      - JuliaCI/julia-test#v1:
          test_args: "general"
      - JuliaCI/julia-coverage#v1: ~
  - label: "JET Tests"
    plugins:
      - JuliaCI/julia#fb9fb9196677350a913f82a125113cc31238ad31:
          version: "1"
      - QuantumSavory/julia-xvfb#a92371896a8ab82b8cbd9a28973003df16a2f58d:
      - JuliaCI/julia-test#v1:
          test_args: "jet"
      - JuliaCI/julia-coverage#v1: ~
  - label: "Example Tests"
    plugins:
      - JuliaCI/julia#fb9fb9196677350a913f82a125113cc31238ad31:
          version: "1"
      - QuantumSavory/julia-xvfb#a92371896a8ab82b8cbd9a28973003df16a2f58d:
      - JuliaCI/julia-test#v1:
          test_args: "example"
      - JuliaCI/julia-coverage#v1: ~
  - label: "Plotting Tests"
    plugins:
      - JuliaCI/julia#fb9fb9196677350a913f82a125113cc31238ad31:
          version: "1"
      - QuantumSavory/julia-xvfb#a92371896a8ab82b8cbd9a28973003df16a2f58d:
      - JuliaCI/julia-test#v1:
          test_args: "plotting"
      - JuliaCI/julia-coverage#v1: ~
    secrets:
      - TILE_CI_KEY
  - label: "Docs"
    branches: "!dependabot/*"
    plugins:
      - JuliaCI/julia#fb9fb9196677350a913f82a125113cc31238ad31:
          version: "1"
      - QuantumSavory/julia-xvfb#a92371896a8ab82b8cbd9a28973003df16a2f58d:
    secrets:
      - DOCUMENTER_KEY
      - ANYTHINGLLM_API_KEY
      - TILE_CI_KEY
    command: |
      julia --project=docs -e 'using Pkg; Pkg.instantiate()'
      julia -tauto --project=docs docs/make.jl
