env:
  CODECOV_TOKEN: 1551efda-9a0d-4cfd-a549-63790fc83605
  JULIA_NUM_THREADS: auto
  QUANTUMSAVORY_PLOT_TEST: true
  
steps:
  - label: "CI Buildkite"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - QuantumSavory/julia-xvfb#v1:
      - JuliaCI/julia-test#v1: ~
      - JuliaCI/julia-coverage#v1:
          codecov: true
